### ISSUE TITLE
failed to run custom build command for four-bar-ui v7.0.1

### ISSUE THREAD

**Issue by 0323pin** [KmolYuan/four-bar-rs#6]
Hi,

After the fix for https://github.com/KmolYuan/four-bar-rs/issues/5 introduced in commit 8f223aac4a07bf0d9cfd2f14e5daff4a1025a609, I did a successful build on NetBSD and confirmed the binary was working.

Apparently, there have been new commits pushed into the same tag as the last one was done 15h ago, https://github.com/KmolYuan/four-bar-rs/releases/tag/v7.0.1

There are several problems, one of which, is the risk of checksum mismatch as the tarball changes for source based builds. It would be preferable to push a minor version update.

The other issue, I'm having is that I can no longer build the package, it now fails with the following error,
```
error: failed to run custom build command for `four-bar-ui v7.0.1 (/scratch/math/four-bar-rs/work/four-bar-rs-7.0.1/four-bar-ui)`

Caused by:
  process didn't exit successfully: `/scratch/math/four-bar-rs/work/four-bar-rs-7.0.1/target/release/build/four-bar-ui-0f6898f2da47d058/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at four-bar-ui/build.rs:6:56:
  range end index 7 out of range for slice of length 0
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
*** Error code 101
```

Any suggestion on how to fix our package build?
Thank you!

**Comment by 0323pin** [comment]
I've fixed the package build for now pulling the source from the original release commit, _I.e._ https://github.com/KmolYuan/four-bar-rs/commit/8f223aac4a07bf0d9cfd2f14e5daff4a1025a609

[pkgsrc commit log](http://mail-index.netbsd.org/pkgsrc-changes/2024/09/05/msg306714.html)

Could you please fix this by the next release? Thanks.
I'd keep this issue open as remainder.

**Comment by KmolYuan** [comment]
I've released a new version.🚀

**Comment by 0323pin** [comment]
Thanks, I'll do a test build and push an update in the coming days.

**Comment by 0323pin** [comment]
@KmolYuan I can confirm this build for me just fine

![2024-09-11-084623_759x276_scrot](https://github.com/user-attachments/assets/dadbb949-28a0-4a83-99dd-657bf341f35f)

NetBSD still uses Rust-1.79 as default, so I'll ask another dev to attempt building with defaults.

Thank you.

**Comment by 0-wiz-0** [comment]
I see this problem again:
```
   Compiling unicode-segmentation v1.11.0
error: failed to run custom build command for `four-bar-ui v7.0.2 (/scratch/wip/four-bar-rs/work/four-bar-rs-7.0.2/four-bar-ui)`

Caused by:
  process didn't exit successfully: `/scratch/wip/four-bar-rs/work/four-bar-rs-7.0.2/target/release/build/four-bar-ui-c4ab740a76d70cfe/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at four-bar-ui/build.rs:6:56:
  range end index 7 out of range for slice of length 0
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
*** Error code 101
```

**Comment by 0323pin** [comment]
@KmolYuan I can confirm that what @0-wiz-0 is seeing is reproduceble on the build machines, http://shadow.netbsd.org/pub/pkgsrc/packages/reports/HEAD/NetBSD-10.0-x86_64/20240916.0656/four-bar-rs-7.0.2/build.log

Although, I cannot reproduce it on my machine. I've successfully built the package 5 times now.

**Comment by KmolYuan** [comment]
@0-wiz-0 Can you provide the log with the environment variable `RUST_BACKTRACE=1`?

**Comment by 0323pin** [comment]
Just for the record, building with `cargo build --release` strips off debug symbols. Use `cargo build` to have them on.

If you manage to finish the build, the binary will be in `target/debug` instead of `target/release`.

**Comment by 0-wiz-0** [comment]
Sure:
```
   Compiling four-bar v7.0.2 (/scratch/math/four-bar-rs/work/four-bar-rs-7.0.2/four-bar)
error: failed to run custom build command for `four-bar-ui v7.0.2 (/scratch/math/four-bar-rs/work/four-bar-rs-7.0.2/four-bar-ui)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/scratch/math/four-bar-rs/work/four-bar-rs-7.0.2/target/release/build/four-bar-ui-c4ab740a76d70cfe/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at four-bar-ui/build.rs:6:56:
  range end index 7 out of range for slice of length 0
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::slice::index::slice_end_index_len_fail_rt
     3: core::slice::index::slice_end_index_len_fail
     4: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
*** Error code 101

```

**Comment by 0323pin** [comment]
🤦‍♂️ @0-wiz-0 can you add `libunwind` to TOOL_DEPENDS?

**Comment by 0-wiz-0** [comment]
This is kind of pointless, I know which part of the code fails. The following patch "fixes" the build:
```
--- four-bar-ui/build.rs.orig   2024-09-18 15:25:35.499852437 +0000
+++ four-bar-ui/build.rs
@@ -1,11 +1,5 @@
 fn main() {
-    if let Ok(hash) = std::process::Command::new("git")
-        .args(["rev-parse", "HEAD"])
-        .output()
-    {
-        let hash = String::from_utf8_lossy(&hash.stdout[..7]);
-        println!("cargo:rustc-env=GIT_HASH={hash}");
-    }
+    println!("cargo:rustc-env=GIT_HASH=12345678");
     #[cfg(windows)]
     {
         let profile = std::env::var("PROFILE").unwrap();
```

When I run 'git rev-parse HEAD' manually (in a shell), I see:
```
# git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git
# echo $?
128
```
so it outputs an error on stderr and reports exit code 128, but the rust code says it went fine.
Perhaps check the exit status? Or the length of the result, before taking a substring?

**Comment by KmolYuan** [comment]
Fixed in 4ea73f7 and released a new version.

**Comment by 0323pin** [comment]
Thank you!

@0-wiz-0 I'll push a package update soon, could you please try it? Thanks!

**Comment by 0-wiz-0** [comment]
Thanks, that's progress, but it still doesn't build - the build expects the `GIT_HASH` environment variable to be setup, but if the `git rev-parse` part fails, it is now not set:
```
   Compiling const-str v0.5.7
error[E0080]: evaluation of constant value failed
  --> /scratch/math/four-bar-rs/work/vendor/const-str-0.5.7/src/__ctfe/unwrap.rs:7:21
   |
7  |             None => panic!("called `Option::unwrap()` on a `None` value"),
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'called `Option::unwrap()` on a `None` value', /scratch/math/four-bar-rs/work/vendor/const-str-0.5.7/src/__ctfe/unwrap.rs:7:21
   |
note: inside `Unwrap::<std::option::Option<&str>>::const_eval`
  --> /scratch/math/four-bar-rs/work/vendor/const-str-0.5.7/src/__ctfe/unwrap.rs:7:21
   |
7  |             None => panic!("called `Option::unwrap()` on a `None` value"),
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `HASH`
  --> four-bar-ui/src/app.rs:18:28
   |
18 |         const HASH: &str = const_str::unwrap!(GIT_HASH);
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `const_str::unwrap` (in Nightly builds, run with -Z macro-backtrace for more info)

note: erroneous constant encountered
  --> four-bar-ui/src/app.rs:19:48
   |
19 |         const_str::concat!("v", VERSION, " (", HASH, ")")
   |                                                ^^^^

note: erroneous constant encountered
  --> four-bar-ui/src/app.rs:19:9
   |
19 |         const_str::concat!("v", VERSION, " (", HASH, ")")
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this note originates in the macro `$crate::to_str` which comes from the expansion of the macro `const_str::concat` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
error: could not compile `four-bar-ui` (bin "four-bar") due to 1 previous error
*** Error code 101

```

**Comment by KmolYuan** [comment]
Fix again in 7e5619f.

**Comment by 0-wiz-0** [comment]
Thank you! That does indeed fix it for me :-)
